// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTNsObject = "t_ns_object"

// TNsObject mapped from table <t_ns_object>
type TNsObject struct {
	ID            int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name          string         `gorm:"column:name;primaryKey" json:"name"`
	Dirname       string         `gorm:"column:dirname;not null;default:/" json:"dirname"`
	Bucket        string         `gorm:"column:bucket;not null" json:"bucket"`
	Cid           string         `gorm:"column:cid" json:"cid"`
	Etag          string         `gorm:"column:etag" json:"etag"`
	ContentLength int64          `gorm:"column:content_length" json:"content_length"`
	ContentType   string         `gorm:"column:content_type" json:"content_type"`
	Version       string         `gorm:"column:version" json:"version"`
	Tags          string         `gorm:"column:tags" json:"tags"`
	Isdir         bool           `gorm:"column:isdir" json:"isdir"`
	Ismarker      bool           `gorm:"column:ismarker" json:"ismarker"`
	Storageclass  string         `gorm:"column:storageclass" json:"storageclass"`
	Acl           string         `gorm:"column:acl;default:private" json:"acl"`
}

// TableName TNsObject's table name
func (*TNsObject) TableName() string {
	return TableNameTNsObject
}
