// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTNsBucketExt = "t_ns_bucket_ext"

// TNsBucketExt mapped from table <t_ns_bucket_ext>
type TNsBucketExt struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID      string         `gorm:"column:uuid;not null" json:"uuid"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name      string         `gorm:"column:name;primaryKey" json:"name"`
	Tag       string         `gorm:"column:tag" json:"tag"`
	Log       string         `gorm:"column:log" json:"log"`
	Acl       string         `gorm:"column:acl;default:private" json:"acl"`
	Policy    string         `gorm:"column:policy" json:"policy"`
	Lifecycle string         `gorm:"column:lifecycle" json:"lifecycle"`
}

// TableName TNsBucketExt's table name
func (*TNsBucketExt) TableName() string {
	return TableNameTNsBucketExt
}
